include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    avoid_void_async: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    depend_on_referenced_packages: true
    package_names: true
    prefer_final_fields: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    require_trailing_commas: true
    secure_pubspec_urls: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_brace_in_string_interps: true
    unnecessary_breaks: true # Check
    use_build_context_synchronously: false

analyzer:
  errors:
    unused_import: error
    invalid_annotation_target: ignore
    avoid_renaming_method_parameters: ignore
    type_annotate_public_apis: ignore
