name: HelloWorld
on:
    push:
        branches:
            - feature/githubActionsConfig
jobs:
    listproject:
        runs-on: macos-latest
        steps:
            - name: Build apk
              run: flutter build apk
