name: Hello World Alertify
on:
    push:
        branches:
            - feature/githubActionsConfig
jobs:
    helloworld:
        runs-on: macos-latest
        steps:
            - name: Hello World
              run: echo 'Hello World'
