name: FLUTTER_MASTER
on:
    push:
        branches:
            - feature/githubActionsConfig # Trigger this workflow on pushes to the specified branch

env:
    flutter_version: '3.19.5' # Define the Flutter version to be used

jobs:
    build-apps:
        runs-on: macos-latest # Run this job on the latest macOS runner
        steps:
            - name: Cache Primes # Step to cache dependencies
              id: cache-primes
              uses: actions/cache@v4
              with:
                  path: |
                      **/nodemodules
                      **/Users/Runner/
                  key: ${{ runner.os }}-primes

            - name: COPY . # Step to copy the repository files
              uses: actions/checkout@v4

            - name: Install - Flutter # Step to install Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: ${{ env.flutter_version }}

            - name: Check - Flutter # Step to check Flutter setup
              run: flutter doctor

            - name: Check - Flutter test # Step to run Flutter tests
              run: flutter test

            - name: Check - Flutter analyze # Step to analyze Flutter code
              run: flutter analyze

            - name: Install - Java # Step to install Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '11'

            - name: Build - Apk # Step to build APK
              run: flutter build apk --release

            # - name: Build - IPA
            #   run: flutter build apk --release --export-options=ios/Runner/ExportOptions.plist

            - name: Export - Artifacts # Step to export build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: android_apk
                  path: build/app/outputs/flutter-apk/app-release.apk

    distribute-apps:
        needs: build-apps # This job depends on the completion of 'build-apps'
        runs-on: ubuntu-latest # Run this job on the latest Ubuntu runner

        steps:
            - name: Download - artifacts # Step to download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: android_apk

            - name: Export - Firebase distribution # Step to upload apk to Firebase distribution
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                  appId: 1:824667822746:android:708274d8bf2695f2f75d23
                  serviceCredentialsFileContent: ${{ secrets.GOOGLE_CREDENTIALS }}
                  groups: testers
                  file: app-release.apk
