name: FLUTTER_MASTER
on:
    push:
        branches:
            - feature/githubActionsConfig

jobs:
    flutter_master_dev:
        runs-on: macos-latest
        steps:
            - name: Cache Primes
              id: cache-primes
              uses: actions/cache@v4
              with:
                  path: |
                      **/nodemodules
                      **/Users/Runner/
                  key: ${{ runner.os }}-primes

            - name: COPY .
              uses: actions/checkout@v4

            - name: Install - Firebase Tools
              run: npm install -g firebase-tools

            - name: Install - Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.5

            - name: Check - Flutter
              run: flutter doctor

            - name: Check - Flutter test
              run: flutter test

            - name: Check - Flutter analyze
              run: flutter analyze

            - name: Install - Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '11'

            - name: Build - Apk
              run: flutter build apk --release

            - uses: actions/upload-artifact@v4
              with:
                  name: apk-and-ipa
                  path: |
                      build/app/outputs/flutter-apk/app-release.apk
