name: FLUTTER_MASTER
on:
    push:
        branches:
            - feature/githubActionsConfig

jobs:
    flutter_master_dev:
        runs-on: macos-latest
        steps:
            - name: COPY .
              uses: actions/checkout@v4
